server: 
      port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/narenk99/spring-cloud-config
          #username: narenk99
          #passphrase: 12345
